export enum BuildingType {
  TOWER_BUILDING = "TOWER_BUILDING",
  INHIBITOR_BUILDING = "INHIBITOR_BUILDING"
}

export enum TowerType {
  OUTER_TURRET = "OUTER_TURRET",
  INNER_TURRET = "INNER_TURRET",
  BASE_TURRET = "BASE_TURRET"
}